# AUTOGENERATED! DO NOT EDIT! File to edit: 00_core.ipynb (unless otherwise specified).

__all__ = ['say_hello', 'HelloSayer']

# Cell
def say_hello(to):
    "Say Hello to somebody"
    return f'Hello {to}!'

# Cell
class HelloSayer:
    "Say hello using the `say_hello` function "

    def __init__(self,to):
        self.to = to

    def say(self):
        "this method calls the `say_hello` function"
        return say_hello(self.to)